### ISSUE TITLE
Advanced search jumps on page

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#63] opened 2016-01-27 22:10 UTC
<a href="https://github.com/emilyville"><img src="https://avatars.githubusercontent.com/u/1307774?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emilyville](https://github.com/emilyville)**
_Tuesday Dec 08, 2015 at 23:42 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/365_

----

on the /for_job_seekers page, clicking "advanced search" jumps to the top of the page. 

This is likely due to a # in the link, and if this were removed I think it would work, though I haven't investigated fully.

**Comment by koconnor719** [comment] 2016-03-02 01:53
we closed this during sprint meeting last week with team.  also,  i don't think we want a "12/10" launch milestone on this correct (just checking b/c i removed it since it's in the past?)

**Comment by emilyville** [comment] 2016-03-02 01:54
Confirmed - this is done and shipped!

**Closed by emilyville** 2016-03-02 01:54 UTC
Labels: 2-in-progress, bug, imported
