### ISSUE TITLE
search functionality - minimum education level

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#143] opened 2016-02-13 02:21 UTC
christine can you pls. research this and see what issue is--you can give robert a call if you need details:)
-----Original Message-----
From: Sanders, Robert, VBAVACO
Sent: Friday, February 12, 2016 02:22 PM Eastern Standard Time
To: VA VETS GOV
Cc: Yale-Loehr, Alex
Subject: Search functionality issue

I would like to flag a search issue regarding the “Minimum Education Level” criteria in the VEC™. When employers attempt to search for candidates using a respective keyword and then the minimum education level drop down, they get an error message. I have attached the two screenshots for further awareness.
 
The system will return results if employers use the minimum education drop down ONLY or if they use the minimum education level ONLY. But if they try to insert a keyword and also filter for minimum education level, they receive an error message.
 
https://mail.google.com/mail/?ui=2&ik=62c76daeff&view=att&th=152d86b4143f3dde&attid=0.2&disp=safe&zw

![screen shot 2016-02-12 at 9 20 51 pm](https://cloud.githubusercontent.com/assets/13770771/13025107/8ac4fea2-d1ce-11e5-87bd-b0c62da30877.png)
![screen shot 2016-02-12 at 9 21 24 pm](https://cloud.githubusercontent.com/assets/13770771/13025114/a16877e2-d1ce-11e5-94bb-c1d310944090.png)

**Comment by koconnor719** [comment] 2016-02-18 02:50
reassiging to @ayaleloehr given it's been escalated by Rosye.  @MarinaMartin

**Comment by ayaleloehr** [comment] 2016-02-18 15:03
On it. I believe the issue is with this line: https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/app/controllers/veterans_controller.rb#L30

Have committed to having this fixed and pushed to production this sprint.

**Comment by koconnor719** [comment] 2016-02-18 16:24
Awesome.
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by ayaleloehr** [comment] 2016-02-22 16:56
Error being thrown was `ActionView::Template::Error (PG::Error: ERROR:  missing FROM-clause entry for table "experiences"
LINE 1: ...d" IS NOT NULL) AND "veterans"."visible" = $1 AND "experienc...`

**Comment by cfeeney-va** [comment] 2016-03-07 14:58
This is an issue with the query we're using to pull data from the database.  The query is built correctly when only one field is filled out, but is missing a key part when they both are.  However, the functionality is a little obscured because it's using an open source library to build the queries.  Looking into where/how this happens.

**Closed** 2016-03-07 19:48 UTC
Labels: 2-in-progress, bug

**Comment by koconnor719** [comment] 2016-03-14 14:27
@cfeeney-va what is status of this; VEC team asking me about this again and estimated time to fix:)  still getting error message when i test it.
<img width="724" alt="screen shot 2016-03-14 at 10 25 12 am" src="https://cloud.githubusercontent.com/assets/13770771/13747585/54d22482-e9cf-11e5-959a-e0ac7d2d6c0c.png">

**Comment by ayaleloehr** [comment] 2016-03-14 14:34
@koconnor719 : @cfeeney-va put the fix in last week. Still needs to be deployed though. Will be fixed in production by the end of the week.
