### ISSUE TITLE
Skills translator skills are lost with linkedin integration?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/veterans-employment-center#108] opened 2016-01-28 18:21 UTC
When I used this, it removed all of my fake infantryman skills. :(

**Comment by cfeeney-va** [comment] 2016-02-24 16:33
Importing from linkedin just posts to createresume, so it deletes anything you've entered already (manual info, skills, military history...)  :(

**Comment by cfeeney-va** [comment] 2016-02-26 17:28
Closed pull request; as discussed current solution will be to put text on the page that warns users to save profile before linkedin import or info will be lost

**Comment by koconnor719** [comment] 2016-03-01 18:04
low priority; move back to backlog.

**Comment by ayaleloehr** [comment] 2016-03-30 14:00
Duplicate of #179, which has more details. closing.

**Closed by ayaleloehr** 2016-03-30 14:00 UTC
